name: Build and Deploy to Netlify

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'psi-reports/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'psi-reports/**'

jobs:
  run-psi:
    name: Generate PSI Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Run Pagespeed Insight
        uses: mazipan/psi-gh-action@1.3.1
        with:
          api_key: ${{ secrets.PSI_API_KEY }}
          urls: |
            https://jefrydco.id/
            https://jefrydco.id/blog/
          devices: |
            mobile
            desktop
          runs: 1
          branch: main
          push_back: true
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Build and Deploy
    needs: [run-psi]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Cache Dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Get Current Time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          utcOffset: '+07:00'

      - name: Peak PSI Reports
        run: yarn log:psi

      - name: Build
        env:
          GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        run: yarn generate

      - name: Deploy
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --message="${{ steps.current-time.outputs.time }}"
